version: "3.7"
services:
  db:
    image: mariadb:10.9.2
    volumes:
        - ./mariadb-data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: jefao123
        MYSQL_DATABASE: routes
        MYSQL_USER: jefao
        MYSQL_PASSWORD: jefao